"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import {
    Sparkles,
    Zap,
    BookOpen,
    Target,
    Globe,
    ArrowRight,
    CheckCircle2,
    Languages,
    Brain,
    Mic,
    PenTool,
    Loader2,
    Mail,
    Lock,
    User,
    Eye,
    EyeOff,
} from "lucide-react";

export default function LandingPage() {
    const router = useRouter();
    const [loading, setLoading] = useState(false);
    const [checkingAuth, setCheckingAuth] = useState(true);
    const [isSignUp, setIsSignUp] = useState(false);
    const [showPassword, setShowPassword] = useState(false);
    const [error, setError] = useState("");
    const [success, setSuccess] = useState("");

    // Form fields
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const [username, setUsername] = useState("");

    // Auth service URL
    const authApiUrl = typeof window !== "undefined"
        ? (window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1"
            ? "http://localhost:8001"
            : `http://${window.location.hostname}:8001`)
        : "http://localhost:8001";

    // Check if user is already logged in
    useEffect(() => {
        const token = localStorage.getItem("auth_token");
        if (token) {
            fetch(`${authApiUrl}/auth/verify`, {
                headers: { Authorization: `Bearer ${token}` }
            })
                .then(res => {
                    if (res.ok) {
                        router.push("/dashboard");
                    } else {
                        localStorage.removeItem("auth_token");
                        localStorage.removeItem("user");
                        setCheckingAuth(false);
                    }
                })
                .catch(() => {
                    setCheckingAuth(false);
                });
        } else {
            setCheckingAuth(false);
        }
    }, [authApiUrl, router]);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setError("");
        setSuccess("");

        try {
            const endpoint = isSignUp ? "/auth/signup" : "/auth/signin";
            const body = isSignUp
                ? { email, password, username }
                : { email, password };

            const res = await fetch(`${authApiUrl}${endpoint}`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(body)
            });

            const data = await res.json();

            if (!res.ok) {
                throw new Error(data.detail || "Authentication failed");
            }

            // Store auth data
            localStorage.setItem("auth_token", data.access_token);
            localStorage.setItem("user", JSON.stringify(data.user));

            if (isSignUp) {
                setSuccess("Account created! Redirecting...");
            }

            // Redirect to dashboard
            setTimeout(() => {
                router.push("/dashboard");
            }, 1000);

        } catch (err: any) {
            setError(err.message || "Something went wrong");
            setLoading(false);
        }
    };

    if (checkingAuth) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-indigo-50 via-white to-purple-50">
                <Loader2 className="w-8 h-8 animate-spin text-indigo-600" />
            </div>
        );
    }

    const features = [
        { icon: Brain, title: "AI-Powered Lessons", description: "Personalized content generated by advanced AI agents" },
        { icon: Languages, title: "Multiple Languages", description: "Learn Chinese, English, Spanish with native structures" },
        { icon: BookOpen, title: "Immersive Stories", description: "Engaging reading passages tailored to your level" },
        { icon: Target, title: "Interactive Quizzes", description: "Test your knowledge with diverse exercise types" },
        { icon: PenTool, title: "Writing Practice", description: "Get AI feedback on your writing assignments" },
        { icon: Mic, title: "Text-to-Speech", description: "Hear authentic pronunciation for all content" }
    ];

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50/30 overflow-hidden">
            {/* Decorative Blobs */}
            <div className="absolute top-0 left-0 w-[500px] h-[500px] bg-gradient-to-br from-indigo-200/30 to-purple-200/30 rounded-full blur-3xl -translate-x-1/2 -translate-y-1/2" />
            <div className="absolute top-1/2 right-0 w-[400px] h-[400px] bg-gradient-to-bl from-pink-200/20 to-indigo-200/20 rounded-full blur-3xl translate-x-1/2" />
            <div className="absolute bottom-0 left-1/3 w-[600px] h-[300px] bg-gradient-to-t from-indigo-100/40 to-transparent rounded-full blur-3xl" />

            {/* Header */}
            <header className="relative z-10">
                <nav className="max-w-7xl mx-auto px-6 py-6 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-600 to-violet-600 flex items-center justify-center shadow-lg shadow-indigo-500/25">
                            <Zap className="w-5 h-5 text-white" />
                        </div>
                        <span className="font-bold text-xl tracking-tight">Language Factory</span>
                    </div>
                </nav>
            </header>

            {/* Hero Section with Auth Form */}
            <section className="relative z-10 max-w-7xl mx-auto px-6 pt-12 pb-16 lg:pt-16 lg:pb-24">
                <div className="grid lg:grid-cols-2 gap-16 items-center">
                    {/* Left Side - Content */}
                    <div className="text-center lg:text-left">
                        <div className="inline-flex items-center gap-2 px-4 py-2 bg-white/80 backdrop-blur-sm border border-indigo-100 rounded-full text-sm font-medium text-indigo-700 shadow-sm mb-8">
                            <Sparkles className="w-4 h-4" />
                            <span>AI-Powered Language Learning</span>
                        </div>

                        <h1 className="text-4xl lg:text-6xl font-extrabold tracking-tight text-slate-900 leading-[1.1] mb-6">
                            Master Languages with{" "}
                            <span className="bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 via-violet-600 to-purple-600">
                                AI Agents
                            </span>
                        </h1>

                        <p className="text-lg lg:text-xl text-slate-600 leading-relaxed max-w-xl mb-8">
                            Generate personalized lessons, practice with interactive quizzes, and get instant AI feedback.
                        </p>

                        <div className="flex flex-wrap items-center justify-center lg:justify-start gap-4 text-sm text-slate-500">
                            <div className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-500" /><span>Free to start</span></div>
                            <div className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-500" /><span>HSK & CEFR levels</span></div>
                            <div className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-500" /><span>3 languages</span></div>
                        </div>

                        {/* Language Showcase */}
                        <div className="flex justify-center lg:justify-start gap-4 mt-10">
                            {[
                                { flag: "🇨🇳", name: "Chinese" },
                                { flag: "🇬🇧", name: "English" },
                                { flag: "🇪🇸", name: "Spanish" }
                            ].map((lang) => (
                                <div key={lang.name} className="px-4 py-3 bg-white/80 backdrop-blur-sm border border-slate-200/60 rounded-xl shadow-md flex items-center gap-3">
                                    <span className="text-2xl">{lang.flag}</span>
                                    <span className="font-semibold text-slate-700">{lang.name}</span>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Right Side - Auth Form */}
                    <div className="relative">
                        <div className="bg-white/90 backdrop-blur-xl rounded-3xl shadow-2xl shadow-indigo-200/50 border border-white/60 p-8 lg:p-10">
                            {/* Tabs */}
                            <div className="flex gap-2 mb-8 p-1 bg-slate-100 rounded-xl">
                                <button
                                    onClick={() => { setIsSignUp(false); setError(""); setSuccess(""); }}
                                    className={`flex-1 py-3 text-sm font-semibold rounded-lg transition-all ${!isSignUp
                                            ? "bg-white text-indigo-700 shadow-md"
                                            : "text-slate-500 hover:text-slate-700"
                                        }`}
                                >
                                    Sign In
                                </button>
                                <button
                                    onClick={() => { setIsSignUp(true); setError(""); setSuccess(""); }}
                                    className={`flex-1 py-3 text-sm font-semibold rounded-lg transition-all ${isSignUp
                                            ? "bg-white text-indigo-700 shadow-md"
                                            : "text-slate-500 hover:text-slate-700"
                                        }`}
                                >
                                    Sign Up
                                </button>
                            </div>

                            <form onSubmit={handleSubmit} className="space-y-5">
                                {isSignUp && (
                                    <div>
                                        <label className="block text-sm font-medium text-slate-700 mb-2">Username</label>
                                        <div className="relative">
                                            <User className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
                                            <input
                                                type="text"
                                                value={username}
                                                onChange={(e) => setUsername(e.target.value)}
                                                placeholder="Your name"
                                                className="w-full pl-12 pr-4 py-3.5 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-all"
                                            />
                                        </div>
                                    </div>
                                )}

                                <div>
                                    <label className="block text-sm font-medium text-slate-700 mb-2">Email</label>
                                    <div className="relative">
                                        <Mail className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
                                        <input
                                            type="email"
                                            value={email}
                                            onChange={(e) => setEmail(e.target.value)}
                                            placeholder="your@email.com"
                                            required
                                            className="w-full pl-12 pr-4 py-3.5 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-all"
                                        />
                                    </div>
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-slate-700 mb-2">Password</label>
                                    <div className="relative">
                                        <Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
                                        <input
                                            type={showPassword ? "text" : "password"}
                                            value={password}
                                            onChange={(e) => setPassword(e.target.value)}
                                            placeholder="••••••••"
                                            required
                                            minLength={6}
                                            className="w-full pl-12 pr-12 py-3.5 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-all"
                                        />
                                        <button
                                            type="button"
                                            onClick={() => setShowPassword(!showPassword)}
                                            className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
                                        >
                                            {showPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
                                        </button>
                                    </div>
                                </div>

                                {error && (
                                    <div className="p-4 bg-red-50 border border-red-200 rounded-xl text-red-600 text-sm">
                                        {error}
                                    </div>
                                )}

                                {success && (
                                    <div className="p-4 bg-emerald-50 border border-emerald-200 rounded-xl text-emerald-600 text-sm">
                                        {success}
                                    </div>
                                )}

                                <button
                                    type="submit"
                                    disabled={loading}
                                    className="w-full py-4 bg-gradient-to-r from-indigo-600 to-violet-600 text-white font-bold rounded-xl shadow-lg shadow-indigo-500/30 hover:shadow-xl hover:shadow-indigo-500/40 hover:-translate-y-0.5 transition-all flex items-center justify-center gap-3 disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    {loading ? (
                                        <Loader2 className="w-5 h-5 animate-spin" />
                                    ) : (
                                        <>
                                            {isSignUp ? "Create Account" : "Sign In"}
                                            <ArrowRight className="w-5 h-5" />
                                        </>
                                    )}
                                </button>
                            </form>

                            <p className="mt-6 text-center text-sm text-slate-500">
                                {isSignUp ? (
                                    <>Already have an account? <button onClick={() => setIsSignUp(false)} className="text-indigo-600 font-medium hover:underline">Sign in</button></>
                                ) : (
                                    <>Don't have an account? <button onClick={() => setIsSignUp(true)} className="text-indigo-600 font-medium hover:underline">Sign up</button></>
                                )}
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            {/* Features Grid */}
            <section className="relative z-10 max-w-7xl mx-auto px-6 py-20">
                <div className="text-center mb-14">
                    <h2 className="text-3xl font-bold text-slate-900 mb-4">
                        Everything you need to <span className="text-indigo-600">master languages</span>
                    </h2>
                </div>

                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {features.map((feature) => (
                        <div key={feature.title} className="group p-7 bg-white/70 backdrop-blur-sm border border-slate-200/60 rounded-2xl hover:bg-white hover:shadow-xl hover:-translate-y-1 transition-all">
                            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-indigo-500 to-violet-500 flex items-center justify-center mb-4 shadow-lg shadow-indigo-500/20 group-hover:scale-110 transition-transform">
                                <feature.icon className="w-6 h-6 text-white" />
                            </div>
                            <h3 className="text-lg font-bold text-slate-900 mb-2">{feature.title}</h3>
                            <p className="text-slate-600 text-sm leading-relaxed">{feature.description}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* Footer */}
            <footer className="relative z-10 border-t border-slate-200/60 bg-white/50 backdrop-blur-sm">
                <div className="max-w-7xl mx-auto px-6 py-6 flex flex-col sm:flex-row items-center justify-between gap-4">
                    <div className="flex items-center gap-2 text-slate-600">
                        <Zap className="w-5 h-5 text-indigo-600" />
                        <span className="font-semibold">Language Factory</span>
                    </div>
                    <p className="text-sm text-slate-500">© 2026 Language Factory. Powered by AI Agents.</p>
                </div>
            </footer>
        </div>
    );
}
